#!/bin/bash
docker rm -f haiwangclient
  docker run  -d --name=haiwangclient \
             -p 3389:3389 \
            --privileged \
            --security-opt seccomp=unconfined \
            --tmpfs /run \
            --tmpfs /run/lock \
            --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
             haiwangio/client
